### ISSUE TITLE
Header for Cache-Control not set properly

### ISSUE THREAD

**Issue by patricekaufmann** [Flowpack/Flowpack.FullPageCache#14]
The cache header being set is `cachecontrol`, but it should be `cache-control` (see https://developer.mozilla.org/de/docs/Web/HTTP/Headers/Cache-Control). This leads to the browser ignoring the cache header, like seen in the attached image. Current cache age exceeds the expected max-age because the `cachecontrol` header is ignored.

![msedge_hhvPtC13gh](https://user-images.githubusercontent.com/41791606/137289235-8bb24bb0-d7a9-4eba-adad-827783cc0ecd.jpg)

Niklas will open a PR to fix this issue in the near future.

**Comment by mficzel** [comment]
@patricekaufmann please check pr #16 and post your test results there.

**Comment by paavo** [comment]
Any plans to merge this fix @mficzel?
